/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_com_jnidemo_JniTest */

#ifndef _Included_test_com_jnidemo_JniTest
#define _Included_test_com_jnidemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_com_jnidemo_JniTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_com_jnidemo_JniTest_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
